[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smart_water_purifier"
version = "2026.0.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.134.0",
    "uvicorn[standard]==0.41.0",
    "python-dotenv==1.2.1",
    "sqlalchemy==2.0.47",
    "asyncpg==0.31.0",
    "sqlmodel==0.0.37",
    "redis[hiredis]==6.4.0",
    "pydantic-settings==2.2.1",
    "email-validator==2.3.0",
    "python-jose[cryptography]==3.5.0",
    "bcrypt==5.0.0",
    "aiomqtt==2.5.1",
    "paho-mqtt==2.1.0",
]

[project.optional-dependencies]
dev = ["alembic", "psycopg", "pytest", "pytest-asyncio", "httpx"]

[tool.setuptools]
packages = ["app"]
