"""replace sensor readings with sensor snapshots

Revision ID: 0555df7bf205
Revises: 9153c2219363
Create Date: 2026-04-28 12:45:57.313482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0555df7bf205'
down_revision: Union[str, Sequence[str], None] = '9153c2219363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_purifier_id', sa.Uuid(), nullable=False),
    sa.Column('tank_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot_type', sa.Enum('INITIAL_RAW', 'FINAL_RESULT', 'ALERT', 'MANUAL_SAMPLE', name='snapshot_type_enum'), nullable=False),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('turbidity', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('water_volume', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['purification_cycles.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.ForeignKeyConstraint(['water_purifier_id'], ['water_purifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_snapshots_cycle_type', 'sensor_snapshots', ['cycle_id', 'snapshot_type'], unique=False)
    op.create_index('idx_sensor_snapshots_purifier_type_recorded', 'sensor_snapshots', ['water_purifier_id', 'snapshot_type', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index('idx_sensor_snapshots_tank_type_recorded', 'sensor_snapshots', ['tank_id', 'snapshot_type', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('ix_sensor_snapshots_cycle_id'), 'sensor_snapshots', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_sensor_snapshots_snapshot_type'), 'sensor_snapshots', ['snapshot_type'], unique=False)
    op.create_index(op.f('ix_sensor_snapshots_tank_id'), 'sensor_snapshots', ['tank_id'], unique=False)
    op.create_index(op.f('ix_sensor_snapshots_water_purifier_id'), 'sensor_snapshots', ['water_purifier_id'], unique=False)
    op.drop_index(op.f('idx_sensor_readings_purifier_recorded'), table_name='sensor_readings')
    op.drop_index(op.f('idx_sensor_readings_tank_recorded'), table_name='sensor_readings')
    op.drop_index(op.f('idx_sensor_readings_tank_sensor_recorded'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_tank_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_water_purifier_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('water_purifier_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tank_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sensor_type', postgresql.ENUM('tds', 'turbidity', 'water_volume', 'temperature', 'ph', name='sensor_type_enum'), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], name=op.f('sensor_readings_tank_id_fkey')),
    sa.ForeignKeyConstraint(['water_purifier_id'], ['water_purifiers.id'], name=op.f('sensor_readings_water_purifier_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sensor_readings_pkey'))
    )
    op.create_index(op.f('ix_sensor_readings_water_purifier_id'), 'sensor_readings', ['water_purifier_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_tank_id'), 'sensor_readings', ['tank_id'], unique=False)
    op.create_index(op.f('idx_sensor_readings_tank_sensor_recorded'), 'sensor_readings', ['tank_id', 'sensor_type', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_sensor_readings_tank_recorded'), 'sensor_readings', ['tank_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_sensor_readings_purifier_recorded'), 'sensor_readings', ['water_purifier_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.drop_index(op.f('ix_sensor_snapshots_water_purifier_id'), table_name='sensor_snapshots')
    op.drop_index(op.f('ix_sensor_snapshots_tank_id'), table_name='sensor_snapshots')
    op.drop_index(op.f('ix_sensor_snapshots_snapshot_type'), table_name='sensor_snapshots')
    op.drop_index(op.f('ix_sensor_snapshots_cycle_id'), table_name='sensor_snapshots')
    op.drop_index('idx_sensor_snapshots_tank_type_recorded', table_name='sensor_snapshots')
    op.drop_index('idx_sensor_snapshots_purifier_type_recorded', table_name='sensor_snapshots')
    op.drop_index('idx_sensor_snapshots_cycle_type', table_name='sensor_snapshots')
    op.drop_table('sensor_snapshots')
    # ### end Alembic commands ###
