"""add mac_address to water_purifiers

Revision ID: 623ac592e50b
Revises: 141ad4ffab38
Create Date: 2026-04-23 10:13:36.410658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '623ac592e50b'
down_revision: Union[str, Sequence[str], None] = '141ad4ffab38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_purifiers', sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.create_index(op.f('ix_water_purifiers_mac_address'), 'water_purifiers', ['mac_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_purifiers_mac_address'), table_name='water_purifiers')
    op.drop_column('water_purifiers', 'mac_address')
    # ### end Alembic commands ###
