"""add sensor reading indexes

Revision ID: 9153c2219363
Revises: b77e564b6982
Create Date: 2026-04-28 01:08:07.454047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9153c2219363'
down_revision: Union[str, Sequence[str], None] = 'b77e564b6982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sensor_readings_purifier_recorded', 'sensor_readings', ['water_purifier_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index('idx_sensor_readings_tank_recorded', 'sensor_readings', ['tank_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index('idx_sensor_readings_tank_sensor_recorded', 'sensor_readings', ['tank_id', 'sensor_type', sa.literal_column('recorded_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sensor_readings_tank_sensor_recorded', table_name='sensor_readings')
    op.drop_index('idx_sensor_readings_tank_recorded', table_name='sensor_readings')
    op.drop_index('idx_sensor_readings_purifier_recorded', table_name='sensor_readings')
    # ### end Alembic commands ###
