"""init

Revision ID: 9e418262e144
Revises: 
Create Date: 2026-04-21 16:29:01.812344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e418262e144'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('water_purifiers',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('device_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('mqtt_topic_base', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('firmware_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code'),
    sa.UniqueConstraint('mqtt_topic_base')
    )
    op.create_index(op.f('ix_water_purifiers_user_id'), 'water_purifiers', ['user_id'], unique=False)
    op.create_table('device_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_purifier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', 'degraded', name='device_status_enum'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['water_purifier_id'], ['water_purifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_status_logs_purifier_time', 'device_status_logs', ['water_purifier_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_device_status_logs_water_purifier_id'), 'device_status_logs', ['water_purifier_id'], unique=False)
    op.create_table('purification_cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('water_purifier_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('running', 'settling', 'completed', 'failed', name='cycle_status_enum'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['water_purifier_id'], ['water_purifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_purification_cycles_purifier_started', 'purification_cycles', ['water_purifier_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_purification_cycles_water_purifier_id'), 'purification_cycles', ['water_purifier_id'], unique=False)
    op.create_table('tanks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('water_purifier_id', sa.Uuid(), nullable=False),
    sa.Column('tank_type', sa.Enum('raw', 'mixing', 'settling', name='tank_type_enum'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['water_purifier_id'], ['water_purifiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('water_purifier_id', 'tank_type', name='uq_tank_per_type')
    )
    op.create_index(op.f('ix_tanks_water_purifier_id'), 'tanks', ['water_purifier_id'], unique=False)
    op.create_table('ai_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purification_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('raw_tds', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('raw_turbidity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('raw_water_level', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('raw_temperature', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('raw_ph', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('recommended_moringa_dose_mg_per_l', sa.Integer(), nullable=False),
    sa.Column('recommended_mixing_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('predicted_is_clean_water', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purification_cycle_id'], ['purification_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decisions_purification_cycle_id'), 'ai_decisions', ['purification_cycle_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('water_purifier_id', sa.Uuid(), nullable=False),
    sa.Column('purification_cycle_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='alert_severity_enum'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purification_cycle_id'], ['purification_cycles.id'], ),
    sa.ForeignKeyConstraint(['water_purifier_id'], ['water_purifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_purifier_created', 'alerts', ['water_purifier_id', 'created_at'], unique=False)
    op.create_index('idx_alerts_unresolved', 'alerts', ['is_resolved', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_water_purifier_id'), 'alerts', ['water_purifier_id'], unique=False)
    op.create_table('cycle_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purification_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('final_tds', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('final_turbidity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('final_ph', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_clean_water', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purification_cycle_id'], ['purification_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_results_purification_cycle_id'), 'cycle_results', ['purification_cycle_id'], unique=True)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_purifier_id', sa.Uuid(), nullable=False),
    sa.Column('tank_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_type', sa.Enum('tds', 'turbidity', 'water_level', 'temperature', 'ph', name='sensor_type_enum'), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.ForeignKeyConstraint(['water_purifier_id'], ['water_purifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sensor_readings_purifier_time', 'sensor_readings', ['water_purifier_id', 'recorded_at'], unique=False)
    op.create_index('idx_sensor_readings_tank_sensor_time', 'sensor_readings', ['tank_id', 'sensor_type', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_readings_tank_id'), 'sensor_readings', ['tank_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_water_purifier_id'), 'sensor_readings', ['water_purifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_water_purifier_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_tank_id'), table_name='sensor_readings')
    op.drop_index('idx_sensor_readings_tank_sensor_time', table_name='sensor_readings')
    op.drop_index('idx_sensor_readings_purifier_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_cycle_results_purification_cycle_id'), table_name='cycle_results')
    op.drop_table('cycle_results')
    op.drop_index(op.f('ix_alerts_water_purifier_id'), table_name='alerts')
    op.drop_index('idx_alerts_unresolved', table_name='alerts')
    op.drop_index('idx_alerts_purifier_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_decisions_purification_cycle_id'), table_name='ai_decisions')
    op.drop_table('ai_decisions')
    op.drop_index(op.f('ix_tanks_water_purifier_id'), table_name='tanks')
    op.drop_table('tanks')
    op.drop_index(op.f('ix_purification_cycles_water_purifier_id'), table_name='purification_cycles')
    op.drop_index('idx_purification_cycles_purifier_started', table_name='purification_cycles')
    op.drop_table('purification_cycles')
    op.drop_index(op.f('ix_device_status_logs_water_purifier_id'), table_name='device_status_logs')
    op.drop_index('idx_device_status_logs_purifier_time', table_name='device_status_logs')
    op.drop_table('device_status_logs')
    op.drop_index(op.f('ix_water_purifiers_user_id'), table_name='water_purifiers')
    op.drop_table('water_purifiers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
