"""make purifier fields required

Revision ID: b77e564b6982
Revises: 04feb9dfc935
Create Date: 2026-04-26 16:48:38.524383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77e564b6982'
down_revision: Union[str, Sequence[str], None] = '04feb9dfc935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('water_purifiers', 'location',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('water_purifiers', 'mac_address',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('water_purifiers', 'firmware_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('water_purifiers', 'firmware_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('water_purifiers', 'mac_address',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('water_purifiers', 'location',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
